
# Site Information
site_name: Zepl Documentation
site_url: http://docs.zepl.com/
site_description: Zepl Documentation Site
site_author: Zepl

# repo_url: https://github.com/ZEPL/zepl-documentation

# Included pages list
nav:
- Welcome: index.md
- User Guide:
  - Notebooks:
    - Sharing Notebooks: guide/sharing_notebooks.md
    - External Notebooks:
      - Apache Zeppelin: guide/zeppelin_integration.md
      - Github: guide/github_integration.md
      - Amazon S3: guide/s3_integration.md
    - Import Notebook: guide/import_notebook.md
    - Export Notebook: guide/export_notebook.md
    - Explore Public Notebooks: guide/exploring_notebooks.md
    - Notebook Versioning: guide/feature_versioning.md
    - Autocompletion: guide/autocompletion_notebooks.md
  - Interpreters:
    - Apache Spark: guide/interpreter/spark.md
    - Python: guide/interpreter/python.md
    - JDBC : guide/interpreter/jdbc.md
    - Config : guide/interpreter/config.md
    - Angular: guide/interpreter/angular.md
  - Accessing Data:
    - Data Sources: guide/datasource/datasource.md
    - Data Source Integrations: guide/datasource/datasource_integration.md
    - Uploading Data: guide/accessing_data.md
  - Resources: guide/resource_mgmt.md
  - Partnerships:
    - Snowflake Partner Connect: guide/partnerships/snowflake_partner_connect.md
  - Authentication:
    - Zepl Account: guide/authentication/zepl_account.md
    - Authentication Providers: guide/authentication/authentication_providers.md
  - Enterprise:
    - Amazon EMR Integration: guide/enterprise/emr_integration.md
    - Custom Image Support: guide/enterprise/custom_image_support.md
    - SaaS Image Builder: guide/enterprise/custom_image_saas.md
    - VPC zcr Utility: guide/enterprise/custom_image_zcr.md
    - Log Console: guide/enterprise/logging_console.md
    - Sagemaker Integration: guide/enterprise/sagemaker.md
- FAQ: faq.md
- Support: support.md

# Theme & Javascript & CSS
theme:
  name: readthedocs
  custom_dir: custom_theme
extra_css:
  - css/extra.css

# Google Analytics
google_analytics: ['UA-38575365-18', 'docs.zepl.com']

# Markdown Extension
markdown_extensions:
    - toc:
        anchorlink: True
    - markdown.extensions.extra

plugins:
    - search
