
# Site Information
site_name: ZEPL Documentation
site_url: http://docs.zepl.com/
site_description: ZEPL Documentation Site
site_author: ZEPL
site_favicon: favicon.ico

# repo_url: https://github.com/ZEPL/zepl-documentation

# Included pages list
pages:
- Welcome: index.md
# - Key Concepts: overview.md
- User Guide:
  - Notebooks:
    - Sharing Notebooks: guide/sharing_notebooks.md
    - External Notebooks:
      - Apache Zeppelin: guide/zeppelin_integration.md
      - Github: guide/github_integration.md
      - Amazon S3: guide/s3_integration.md
    - Import Notebook: guide/import_notebook.md
    - Export Notebook: guide/export_notebook.md
    - Explore Public Notebooks: guide/exploring_notebooks.md
    - Uploading Data: guide/accessing_data.md
    - Notebook Versioning: guide/feature_versioning.md
    - Autocompletion: guide/autocompletion_notebooks.md
  - Interpreters:
    - Apache Spark: guide/interpreter/spark.md
    - Python: guide/interpreter/python.md
    - JDBC : guide/interpreter/jdbc.md
    - Config : guide/interpreter/config.md
    - Angular: guide/interpreter/angular.md
  - Resources: guide/resource_mgmt.md
  - Enterprise:
    - Amazon EMR Integration: guide/emr_integration.md
    - Login Support: guide/enterprise/login_support.md
    - Custom Image Support: guide/enterprise/custom_image_support.md
    - Log Console: guide/enterprise/logging_console.md
    - Sagemaker Integration: guide/enterprise/sagemaker.md
# - Release Notes: release_note.md
- FAQ: faq.md
- Support: support.md

# Theme & Javascript & CSS
theme_dir: 'custom_theme'
extra_javascript:
  - js/extra.js
extra_css:
  - css/extra.css

# Google Analytics
google_analytics: ['UA-38575365-18', 'docs.zepl.com']

# Markdown Extension
markdown_extensions:
    - toc:
        anchorlink: True
    - markdown.extensions.extra
