
# Site Information
site_name: ZEPL Documentation
site_url: http://docs.zepl.com/
site_description: ZEPL Documentation Site
site_author: ZEPL
site_favicon: favicon.ico

# repo_url: https://github.com/ZEPL/zepl-documentation

# Included pages list
pages:
- Welcome: index.md
- FAQ: faq.md
# - Key Concepts: overview.md
- User Guide:
    - User Guide: guide/user_guide.md
    - Sharing Notebooks: guide/sharing_notebooks.md
    - External Notebooks:
      - Apache Zeppelin: guide/zeppelin_integration.md
      - Github: guide/github_integration.md
      - Amazon S3: guide/s3_integration.md
    - Import Notebook: guide/import_notebook.md
    - Explore Public Notebooks: guide/exploring_notebooks.md
# - Release Notes: release_note.md
- Support: support.md

# Theme & Javascript & CSS
theme_dir: 'custom_theme'
extra_javascript:
  - js/extra.js
extra_css:
  - css/extra.css

# Google Analytics
google_analytics: ['UA-38575365-18', 'docs.zepl.com']

# Markdown Extension
markdown_extensions:
    - toc:
        anchorlink: True
